stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: golang:1.11
  script:
    - go test

build:
  stage: build
  
deploy_review:
  stage: deploy
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.ingress.oldsmail.com
  only:
    - branches
  except:
    - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  environment:
    name: production
    url: https://prod.oldsmail.com
  when: manual
  only:
  - master
